### ISSUE TITLE
Segmentation fault when map contains unknown value

### ISSUE THREAD

**Issue by mhulscher** [isometry/terraform-provider-deepmerge#48]
Hi! I really love this provider and I'm thinking that perhaps I'm stretching its use-case a little bit too much.

I assign the result of `mergo()` to a local. The passed maps contain references to values that are only available after some other terraform resources have been applied. `mergo` works well when the dependant resources already exist, but when planning/applying for the first time, `mergo` fails.

I don't know if this can be fixed. Below is the stacktrace. Would love it if this could be made to work.

```
❯ terraform version
OpenTofu v1.8.4
on linux_amd64
```

```
* Failed to execute "tofu apply -auto-approve -input=false" in ./.terragrunt-cache/6mvrWJOv-yVpQOdgmZnis5Lazws/n49QLCs7EgVUtHotfbpps5a-ASY
  ╷
  │ Error: Error in function call
  │ 
  │   on ingress.tf line 134, in locals:
  │  134:     config.name => provider::deepmerge::mergo(
  │  135:       local.karpenter_node_class_defaults,
  │  136:       {
  │  137:         metadata = {
  │  138:           name = config.name
  │  139:         }
  │  140:         spec = {
  │  141:           securityGroupSelectorTerms = [
  │  142:             { id = aws_security_group.ingress_karpenter_node_class[config.name].id },
  │  143:           ]
  │  144:         }
  │  145:       },
  │  146:       "append"
  │  147:     ) if config.nodes.provisioner == "karpenter"
  │     ├────────────────
  │     │ aws_security_group.ingress_karpenter_node_class is object with 1 attribute "ingress-nginx"
  │     │ config.name is "ingress-nginx"
  │     │ local.karpenter_node_class_defaults is object with 3 attributes
  │ 
  │ Call to function "provider::deepmerge::mergo" failed: rpc error: code =
  │ Canceled desc = context canceled.
  ╵
  
  Stack trace from the terraform-provider-deepmerge_v0.3.0 plugin:
  
  panic: runtime error: invalid memory address or nil pointer dereference
  [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa7596a]
  
  goroutine 51 [running]:
  github.com/isometry/terraform-provider-deepmerge/internal/helpers.EncodeValue({0x0, 0x0})
  	github.com/isometry/terraform-provider-deepmerge/internal/helpers/encode.go:16 +0x2a
  github.com/isometry/terraform-provider-deepmerge/internal/helpers.EncodeValue({0xd2c080, 0xc000484ee8})
  	github.com/isometry/terraform-provider-deepmerge/internal/helpers/encode.go:39 +0x86
  github.com/isometry/terraform-provider-deepmerge/internal/helpers.EncodeObject({0xc0004167e0?, 0xc0004143c0?, 0x20?})
  	github.com/isometry/terraform-provider-deepmerge/internal/helpers/encode.go:92 +0x231
  github.com/isometry/terraform-provider-deepmerge/internal/helpers.EncodeValue({0xd2bb28, 0xc0004850c8})
  	github.com/isometry/terraform-provider-deepmerge/internal/helpers/encode.go:29 +0x1dd
  github.com/isometry/terraform-provider-deepmerge/internal/helpers.EncodeObject({0xc0004161b0?, 0xc0004140f0?, 0x2?})
  	github.com/isometry/terraform-provider-deepmerge/internal/helpers/encode.go:92 +0x231
  github.com/isometry/terraform-provider-deepmerge/internal/helpers.EncodeValue({0xd2bb28, 0xc0004850e0})
  	github.com/isometry/terraform-provider-deepmerge/internal/helpers/encode.go:29 +0x1dd
  github.com/isometry/terraform-provider-deepmerge/internal/helpers.EncodeValue({0xd2c080, 0xc0004852a8})
  	github.com/isometry/terraform-provider-deepmerge/internal/helpers/encode.go:39 +0x86
  github.com/isometry/terraform-provider-deepmerge/internal/helpers.Mergo({0xd29628, 0xc000136960}, {0xc00041e6f0, 0x2, 0xadb960?}, {0xc000483f00, 0x2, 0x2})
  	github.com/isometry/terraform-provider-deepmerge/internal/helpers/mergo.go:16 +0x114
  github.com/isometry/terraform-provider-deepmerge/internal/provider.MergoFunction.Run({}, {0xd29628, 0xc000136960}, {{{0xc000483830?, 0x0?, 0x0?}}}, 0xc000484c18)
  	github.com/isometry/terraform-provider-deepmerge/internal/provider/mergo_function.go:99 +0x971
  github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CallFunction(0x0?, {0xd29628, 0xc000136960}, 0xc00017c1e0, 0xc0001f9580)
  	github.com/hashicorp/terraform-plugin-framework@v1.12.0/internal/fwserver/server_callfunction.go:50 +0x2f5
  github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).CallFunction(0xc0001fc1e0, {0xd29628?, 0xc000136870?}, 0xc0001367b0)
  	github.com/hashicorp/terraform-plugin-framework@v1.12.0/internal/proto6server/server_callfunction.go:52 +0x55a
  github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).CallFunction(0xc000208500, {0xd29628?, 0xc0001361b0?}, 0xc0001340f0)
  	github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov6/tf6server/server.go:965 +0x4c8
  github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_CallFunction_Handler({0xbeaca0, 0xc000208500}, {0xd29628, 0xc0001361b0}, 0xc00035a180, 0x0)
  	github.com/hashicorp/terraform-plugin-go@v0.24.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:635 +0x1a6
  google.golang.org/grpc.(*Server).processUnaryRPC(0xc00019ce00, {0xd29628, 0xc000136120}, {0xd2f220, 0xc00017e000}, 0xc00013a000, 0xc00026fe00, 0x120e2d0, 0x0)
  	google.golang.org/grpc@v1.67.1/server.go:1394 +0xe2b
  google.golang.org/grpc.(*Server).handleStream(0xc00019ce00, {0xd2f220, 0xc00017e000}, 0xc00013a000)
  	google.golang.org/grpc@v1.67.1/server.go:1805 +0xe8b
  google.golang.org/grpc.(*Server).serveStreams.func2.1()
  	google.golang.org/grpc@v1.67.1/server.go:1029 +0x7f
  created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 20
  	google.golang.org/grpc@v1.67.1/server.go:1040 +0x125
  
  Error: The terraform-provider-deepmerge_v0.3.0 plugin crashed!
  
  This is always indicative of a bug within the plugin. It would be immensely
  helpful if you could report the crash with the plugin's maintainers so that it
  can be fixed. The output above should help diagnose the issue.
```

**Comment by isometry** [comment]
Thanks for the bug report! This is certainly intended to work, so I'll see what can be done.

**Comment by isometry** [comment]
So, my testing suggests that despite the boilerplate (and normally accurate) report that the bug is in the provider, this actually looks to be the result of a bug in OpenTofu's handling of unknown values when it comes to their implementation of custom function calls.

The `terraform-plugin-framework` explicitly permits custom functions to specify whether individual function parameters support unknown values. The `mergo` function's single variadic parameter is configured with the default behaviour (`AllowUnknownValues: false`), meaning that all function calls with any unknown (`(known after apply)`) values should have the function itself return `(known after apply)`. This is exactly what it does with HashiCorp Terraform… but in my simple testing OpenTofu does *not* respect `AllowUnknownValues` and instead passes unknown values as zero values to custom functions. This is *bad* because it means that if you happen to use a custom function in an output, or indeed *anywhere* that drives other behaviour, the result is outright *wrong* and requires at least two applies to reach a stable state.

Reproduction module:

```terraform
terraform {
  required_providers {
    deepmerge = { source = "isometry/deepmerge" }
  }
}

resource "terraform_data" "test" {
  input            = { test = "test" }
  triggers_replace = [timestamp()]
}

output "builtin" {
  value = jsonencode(terraform_data.test.output)
}

output "custom" {
  value = provider::deepmerge::mergo({ test = terraform_data.test.output })
}
```

With HashiCorp Terraform v1.9.8:

```console
$ terraform plan

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # terraform_data.test will be created
  + resource "terraform_data" "test" {
      + id               = (known after apply)
      + input            = {
          + test = "test"
        }
      + output           = (known after apply)
      + triggers_replace = [
          + (known after apply),
        ]
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + builtin = (known after apply)
  + custom  = (known after apply)
```

Whilst with OpenTofu v1.8.4:

```console
$ tofu plan

╷
│ Error: Error in function call
│ 
│   on main.tf line 17, in output "custom":
│   17:   value = provider::deepmerge::mergo({ test = terraform_data.test.output })
│     ├────────────────
│     │ while calling provider::deepmerge::mergo(maps...)
│ 
│ Call to function "provider::deepmerge::mergo" failed: rpc error: code = Unavailable desc = error reading from server: EOF.
╵

Stack trace from the terraform-provider-deepmerge plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x100efeb64]

...elided...

Error: The terraform-provider-deepmerge plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Just as you reported.

I'm going to add a dumb workaround to the provider to avoid the crash, but this issue _needs_ to be reported and fixed upstream. As-is, with OpenTofu it's positively dangerous to use *any* custom function with unknown values and expect plans to be either stable or accurate.

**Comment by isometry** [comment]
v0.3.1 includes the workaround for the crash.

@mhulscher : do you want to report the issue upstream, or shall I?

**Comment by cam72cam** [comment]
As mentioned in the linked OpenTofu issue, it's unclear if what terraform is doing should be considered a bug.  As far as I can tell from the discussion (without looking at any code obviously), terraform short cuts any provider function with "Partially Unknown" values if "AllowUnknownValues = false".  OpenTofu does not do this and uses the standard message encoding to let the provider function itself determine how it wants to respond to partially unknown inputs.

Here's a suggested patch, which I'm happy to PR:
```patch
diff --git a/internal/helpers/encode.go b/internal/helpers/encode.go
index ce141eb..574ce37 100644
--- a/internal/helpers/encode.go
+++ b/internal/helpers/encode.go
@@ -6,19 +6,26 @@
 package helpers
 
 import (
+       "errors"
        "fmt"
 
        "github.com/hashicorp/terraform-plugin-framework/attr"
        "github.com/hashicorp/terraform-plugin-framework/types/basetypes"
 )
 
+var ErrUnknownValue = errors.New("Unknow value")
+
 func EncodeValue(v attr.Value) (any, error) {
        // Avoid nil pointer deref with broken OpenTofu custom function
        // implementation that passes unknown values as zero values.
-       if v == nil || v.IsNull() {
+       if v.IsNull() {
                return nil, nil
        }
 
+       if v.IsUnknown() {
+               return nil, ErrUnknownValue
+       }
+
        switch vv := v.(type) {
        case basetypes.StringValue:
                return vv.ValueString(), nil
diff --git a/internal/helpers/mergo.go b/internal/helpers/mergo.go
index 2a6ac81..ce80066 100644
--- a/internal/helpers/mergo.go
+++ b/internal/helpers/mergo.go
@@ -12,8 +12,13 @@ import (
 
 func Mergo(ctx context.Context, objs []types.Dynamic, opts ...func(*mergo.Config)) (merged types.Dynamic, diags diag.Diagnostics) {
        maps := make([]map[string]any, len(objs))
+       containsUnknown := false
        for i, obj := range objs {
                x, err := EncodeValue(obj)
+               if err == ErrUnknownValue {
+                       containsUnknown = true
+                       continue
+               }
                if err != nil {
                        diags.Append(diag.NewErrorDiagnostic(fmt.Sprintf("Error encoding argument %d", i+1), err.Error()))
                        return
@@ -25,6 +30,9 @@ func Mergo(ctx context.Context, objs []types.Dynamic, opts ...func(*mergo.Config
                        maps[i] = y
                }
        }
+       if containsUnknown {
+               return types.DynamicUnknown(), nil
+       }
 
        dst := maps[0]
        for i, m := range maps[1:] {
```

**Comment by isometry** [comment]
> +       if v.IsUnknown() {
> 
> +               return nil, ErrUnknownValue
> 
> +       }

@cam72cam : this was the first thing I tried. The problem is that in the reproduction case, `v` is literally `nil`, and so doing anything other comparing it to `nil` triggers a panic.

Why is it that you think the documented and implemented behaviour of HC Terraform is wrong? As the code says, unless a parameter explicitly sets `AllowUnknown values: true` then it should only be capped with wholly known values.

**Comment by mhulscher** [comment]
@isometry I tested with the new patch and it seems to work. Feel free to close, or to leave open until the upstream is resolved. Thanks again.

**Comment by isometry** [comment]
I'll leave this open until @cam72cam 's upstream PR to fix OpenTofu is merged and released. Honestly, I'd prefer the provider to crash rather than be responsible for the impact of its returning inaccurate results when fed uninitialised structs :-)

**Comment by mhulscher** [comment]
Understandable. Since I'm using the alekc/kubectl terraform provider to apply kubernetes manifests, generated in-part by the mergo function, I notice that there is now an inconsistency between what the manifest will look like at plan time, and what it will look like at apply time. Most likely because of the inaccurate results that you mention. In my specific use-case, the patch to deepmerge doesn't solve my problem. So I agree, keeping this open is probably for the better.
